# optional platform, remove it if not needed
FROM --platform=linux/amd64 python:3.12-alpine 

WORKDIR /apps/

RUN apk add gcc libc-dev libffi-dev

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ./api ./api
COPY ./core ./core
COPY ./migrations ./migrations
COPY ./psql_db ./psql_db

COPY yoyo.ini .
COPY main.py .

CMD ["fastapi", "run"]
