ENDPOINT_ROOT = '/api/v1'


API_HOME = ENDPOINT_ROOT + '/'
API_TOKEN = ENDPOINT_ROOT + '/token'
API_LOGIN = ENDPOINT_ROOT + '/login'
API_REGISTER = ENDPOINT_ROOT + '/register'
API_USER = ENDPOINT_ROOT + '/user'